#!/usr/bin/env python3
"""
docs_refresh.py — synchronize 'Generated by Oracle' headers and 'Last Updated' timestamps
across Markdown documentation files in the Oracle Portfolio Manager project.

Usage:
    python automation/docs_refresh.py
"""

from __future__ import annotations
import pathlib as _p
import re
from datetime import datetime, UTC

# ------------------------- Config -------------------------
SEARCH_GLOBS = [
    "*.md",           # root-level docs like README*.md, CHANGELOG*.md
    "docs/*.md",      # docs/ subfolder
]
# Patterns to detect/update
HEADER_RE = re.compile(r"<!--\s*Generated by Oracle\s*—\s*.*?UTC\s*-->", re.IGNORECASE | re.DOTALL)
LAST_UPDATED_RE = re.compile(r"^(\*\*Last Updated:\*\*)\s*\d{4}-\d{2}-\d{2}\s*$", re.MULTILINE)
# ---------------------------------------------------------

def _iter_markdown_files() -> list[_p.Path]:
    seen: set[_p.Path] = set()
    for pat in SEARCH_GLOBS:
        for p in _p.Path(".").glob(pat):
            if p.is_file() and p.suffix.lower() == ".md":
                seen.add(p.resolve())
    return sorted(seen)

def _refresh_one(path: _p.Path, date_iso: str, header_comment: str) -> tuple[bool, str]:
    text = path.read_text(encoding="utf-8")
    original = text

    # Header: replace if present, else insert at very top
    if HEADER_RE.search(text):
        text = HEADER_RE.sub(header_comment, text)
    else:
        text = header_comment + "\n" + text

    # Footer: update Last Updated line(s) if present
    if LAST_UPDATED_RE.search(text):
        text = LAST_UPDATED_RE.sub(rf"\1 {date_iso}", text)

    if text != original:
        path.write_text(text, encoding="utf-8")
        return True, "UPDATED"
    else:
        return False, "UNCHANGED"

def main() -> int:
    now_utc = datetime.now(UTC)
    date_iso = now_utc.strftime("%Y-%m-%d")
    header_comment = f"<!-- Generated by Oracle — {now_utc.strftime('%Y-%m-%d %H:%M UTC')} -->"

    files = _iter_markdown_files()
    if not files:
        print("[WARN] No Markdown files found in root or docs/. Nothing to do.")
        return 0

    print(f"[INFO] Refreshing documentation timestamps → {date_iso}")
    updated = 0
    for f in files:
        try:
            changed, status = _refresh_one(f, date_iso, header_comment)
            print(f"[{status}] {f.relative_to(_p.Path('.').resolve())}")
            if changed:
                updated += 1
        except Exception as e:
            print(f"[ERROR] {f}: {e}")

    print(f"[DONE] Documentation refresh complete. Files updated: {updated}/{len(files)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
